spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/scrapper
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

  liquibase:
    enabled: false

app:
  scheduler:
    interval: 15S
  link-update-age: 15S
  database-access-type: jdbc
  use-queue: true
  rabbitmq:
    exchange: bot.exchange
    queue: bot.queue
    bind: bot


server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

github-client:
  base-url: https://api.github.com
  api-key: ${GITHUB_API_KEY}
  api-version: 2022-11-28

stackoverflow-client:
  base-url: https://api.stackexchange.com/2.3
  api-key: ${STACKOVERFLOW_API_KEY}
