name: Bot module

on:
  push:
    paths:
      - 'bot/**'
      
  pull_request:
    paths:
      - 'bot/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Maven package
        run: mvn package -pl bot -am

      - name: Build  image
        run: docker build . -t emiask/bot:latest

