name: Bot module

on:
  push:
    paths:
      - 'bot/**'
      
  pull_request:
    paths:
      - 'bot/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - run: ls -la
      - run: echo $GITHUB_SHA
      - name: Maven package
        run: mvn clean install


