name: Scrapper module

on:
  push:
    paths:
      - 'scrapper/**'

  pull_request:
    paths:
      - 'scrapper/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Maven package
        run: mvn package -pl scrapper -am


